// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cmsGame.Data;

namespace cmsGame.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20230412071844_newCmsDBMigrate5")]
    partial class newCmsDBMigrate5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cmsGame.Models.Upload.UploadAndroidGameModel", b =>
                {
                    b.Property<int>("Game_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Android_Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banner_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Game_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Game_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Game_Type_Code")
                        .HasColumnType("int");

                    b.Property<string>("Install")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Owner_Code")
                        .HasColumnType("int");

                    b.Property<string>("Physical_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preview_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upload_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Upload_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Game_Code");

                    b.ToTable("tbl_Game_Android");
                });
#pragma warning restore 612, 618
        }
    }
}
