// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cmsGame.Data;

namespace cmsGame.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20230412064320_newCmsDBMigrate")]
    partial class newCmsDBMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cmsGame.Models.Upload.UploadAndroidGameModel", b =>
                {
                    b.Property<int>("GameCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AndroidVersion")
                        .HasColumnType("int");

                    b.Property<int>("BannerUrl")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("Expire")
                        .HasColumnType("int");

                    b.Property<int>("GamePrice")
                        .HasColumnType("int");

                    b.Property<int>("GameTitle")
                        .HasColumnType("int");

                    b.Property<int>("GameTypeCode")
                        .HasColumnType("int");

                    b.Property<int>("Install")
                        .HasColumnType("int");

                    b.Property<int>("InstallK")
                        .HasColumnType("int");

                    b.Property<int>("OwnerCode")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalLocation")
                        .HasColumnType("int");

                    b.Property<int>("PreviewURL")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("UploadBy")
                        .HasColumnType("int");

                    b.Property<int>("Upload_Date")
                        .HasColumnType("int");

                    b.HasKey("GameCode");

                    b.ToTable("tbl_Game_Android");
                });
#pragma warning restore 612, 618
        }
    }
}
