// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cmsGame.Data;

namespace cmsGame.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20230412065442_newCmsDBMigrate1")]
    partial class newCmsDBMigrate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cmsGame.Models.Upload.UploadAndroidGameModel", b =>
                {
                    b.Property<int>("Game_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Android_Version")
                        .HasColumnType("int");

                    b.Property<int>("BannerUrl")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("Expire")
                        .HasColumnType("int");

                    b.Property<int>("Game_Price")
                        .HasColumnType("int");

                    b.Property<int>("Game_Title")
                        .HasColumnType("int");

                    b.Property<int>("Game_Type_Code")
                        .HasColumnType("int");

                    b.Property<int>("Install")
                        .HasColumnType("int");

                    b.Property<int>("InstallK")
                        .HasColumnType("int");

                    b.Property<int>("Owner_Code")
                        .HasColumnType("int");

                    b.Property<int>("Physical_Location")
                        .HasColumnType("int");

                    b.Property<int>("Preview_URL")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Upload_By")
                        .HasColumnType("int");

                    b.Property<int>("Upload_Date")
                        .HasColumnType("int");

                    b.HasKey("Game_Code");

                    b.ToTable("tbl_Game_Android");
                });
#pragma warning restore 612, 618
        }
    }
}
